# Generated by Django 5.1.6 on 2025-02-24 13:43

import django.db.models.deletion
import functools
import service.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to=functools.partial(service.utils.image_file_path, *(), **{'folder': 'actors'}))),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TheatreHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rows', models.PositiveIntegerField()),
                ('seats_in_row', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to=functools.partial(service.utils.image_file_path, *(), **{'folder': 'plays'}))),
                ('actors', models.ManyToManyField(related_name='plays', to='theatre.actor')),
                ('genres', models.ManyToManyField(related_name='plays', to='theatre.genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.DateTimeField()),
                ('image', models.ImageField(null=True, upload_to=functools.partial(service.utils.image_file_path, *(), **{'folder': 'performances'}))),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.play')),
                ('theatre_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.theatrehall')),
            ],
            options={
                'ordering': ['-show_time', 'theatre_hall'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('seat', models.PositiveIntegerField()),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='theatre.performance')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='theatre.reservation')),
            ],
            options={
                'ordering': ['row', 'seat'],
                'unique_together': {('row', 'seat', 'performance')},
            },
        ),
    ]
